-- 1- When is the peak season of our ecommerce ?

SELECT * FROM (
SELECT 
d.QUARTER,
d.YEAR,
COUNT(o.ORDER_ID) AS ORDER_COUNT
FROM DWH.FCT_ORDERS o
INNER JOIN DWH.DIM_DATE d 
ON o.ORDER_DATE_ID = d.DATE_ID
GROUP BY d.QUARTER, d.YEAR
ORDER BY ORDER_COUNT DESC
)
WHERE ROWNUM = 1;


-- 2- What time users are most likely make an order or using the ecommerce app?

SELECT * FROM (
SELECT 
ORDER_HOUR AS ORDER_HOUR,
COUNT(ORDER_ID) AS ORDER_COUNT
FROM DWH.FCT_ORDERS
GROUP BY ORDER_HOUR
ORDER BY ORDER_COUNT DESC
)
WHERE ROWNUM=1;


-- 3- What is the preferred way to pay in the ecommerce?

SELECT * FROM (
SELECT 
PAYMENT_TYPE,
COUNT(*) AS PAYMENT_COUNT
FROM DWH.FCT_PAYMENTS
GROUP BY PAYMENT_TYPE
ORDER BY PAYMENT_COUNT DESC
)
WHERE ROWNUM = 1;


-- 4- How many installment is usually done when paying in the ecommerce?

SELECT * FROM (
SELECT 
PAYMENT_INSTALLMENTS,
COUNT(*) AS INSTALLMENTS_COUNT
FROM DWH.FCT_PAYMENTS
GROUP BY PAYMENT_INSTALLMENTS
ORDER BY INSTALLMENTS_COUNT DESC
)
WHERE ROWNUM = 1;

-- 5- What is the average spending time for user for our ecommerce?

SELECT 
AVG(SPENDING_TIME) AS AVG_SPENDING_TIME
FROM DWH.FCT_ORDERS
WHERE DELIVERY_DATE_ID IS NOT NULL;

-- 6- What is the frequency of purchase on each state?

SELECT 
c.CUSTOMER_STATE,
COUNT(o.ORDER_ID) AS ORDER_COUNT
FROM DWH.FCT_ORDERS o
INNER JOIN DWH.DIM_CUSTOMERS c 
ON o.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_STATE
ORDER BY ORDER_COUNT DESC;


-- 7- Which logistic route that have heavy traffic in our ecommerce?

SELECT * FROM (
SELECT 
s.SELLER_CITY AS SELLER_CITY,
c.CUSTOMER_CITY AS CUSTOMER_CITY,
COUNT(*) AS ORDER_COUNT
FROM DWH.FCT_ORDER_ITEMS oi
INNER JOIN DWH.FCT_ORDERS o ON oi.ORDER_ID = o.ORDER_ID
INNER JOIN DWH.DIM_SELLERS s ON oi.SELLER_ID = s.SELLER_ID
INNER JOIN DWH.DIM_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY s.SELLER_CITY, c.CUSTOMER_CITY
ORDER BY ORDER_COUNT DESC
)
WHERE ROWNUM = 1;

-- 8- How many late delivered order in our ecommerce? Are late order affecting the customer satisfaction?

SELECT 
COUNT(o.ORDER_ID) AS LATE_DELIVERED_ORDERS
FROM DWH.FCT_ORDERS o
WHERE o.DELIVERY_DATE_ID > o.ESTIMATED_DELIVERY_DATE_ID;

-- 9- How long are the delay for delivery / shipping process in each state?

SELECT 
c.CUSTOMER_STATE,
AVG(o.DELIVERY_DELAY_DAYS) AS AVG_DELIVERY_DELAY
FROM DWH.FCT_ORDERS o
INNER JOIN DWH.DIM_CUSTOMERS c 
ON o.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_STATE
ORDER BY AVG_DELIVERY_DELAY DESC;

-- 10- How long are the difference between estimated delivery time and actual delivery time in each state?

SELECT 
c.CUSTOMER_STATE,
AVG(d1.FULL_DATE - d2.FULL_DATE) AS AVG_DELIVERY_DIFF_DAYS
FROM DWH.FCT_ORDERS o
INNER JOIN DWH.DIM_CUSTOMERS c 
ON o.CUSTOMER_ID = c.CUSTOMER_ID
INNER JOIN DWH.DIM_DATE d1 
ON o.ESTIMATED_DELIVERY_DATE_ID = d1.DATE_ID
INNER JOIN DWH.DIM_DATE d2 
ON o.DELIVERY_DATE_ID = d2.DATE_ID
GROUP BY c.CUSTOMER_STATE
ORDER BY AVG_DELIVERY_DIFF_DAYS DESC;

