INSERT INTO DWH.FCT_PAYMENTS (PAYMENT_ID, ORDER_ID, PAYMENT_SEQUENTIAL, PAYMENT_TYPE, PAYMENT_INSTALLMENTS, PAYMENT_VALUE)
SELECT 
    ROW_NUMBER() OVER (ORDER BY p.ORDER_ID, p.PAYMENT_SEQUENTIAL) AS PAYMENT_ID, -- Generate a unique ID
    p.ORDER_ID,
    p.PAYMENT_SEQUENTIAL,
    p.PAYMENT_TYPE,
    p.PAYMENT_INSTALLMENTS,
    p.PAYMENT_VALUE
FROM STG.STG_PAYMENTS p;
