INSERT INTO DWH.FCT_ORDER_ITEMS (ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, SELLER_ID, PRICE, SHIPPING_COST)
SELECT 
    oi.ORDER_ID,
    oi.ORDER_ITEM_ID,
    oi.PRODUCT_ID,
    oi.SELLER_ID,
    oi.PRICE,
    oi.SHIPPING_COST
FROM 
    STG.STG_ORDER_ITEMS oi;
