INSERT INTO DWH.DIM_CUSTOMERs (
    CUSTOMER_ID,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_ZIP_CODE
)
SELECT 
    u.USER_NAME AS USER_ID,
    u.CUSTOMER_CITY,
    u.CUSTOMER_STATE,
    u.CUSTOMER_ZIP_CODE
FROM (
    SELECT 
        USER_NAME, 
        CUSTOMER_CITY, 
        CUSTOMER_STATE, 
        CUSTOMER_ZIP_CODE,
        ROW_NUMBER() OVER (PARTITION BY USER_NAME ORDER BY USER_NAME) AS row_num
    FROM STG.STG_USERS u
) u
WHERE u.row_num = 1;