CREATE TABLE "STG"."STG_FEEDBACK" 
   (	"FEEDBACK_ID" VARCHAR2(50), 
	"ORDER_ID" VARCHAR2(50), 
	"FEEDBACK_SCORE" NUMBER(3,0), 
	"FEEDBACK_FORM_SENT_DATE" DATE, 
	"FEEDBACK_ANSWER_DATE" DATE
   );


CREATE TABLE "STG"."STG_ORDERS" 
   (	"ORDER_ID" VARCHAR2(50), 
	"USER_NAME" VARCHAR2(50), 
	"ORDER_STATUS" VARCHAR2(50), 
	"ORDER_DATE" DATE, 
	"ORDER_APPROVED_DATE" DATE, 
	"PICKUP_DATE" DATE, 
	"DELIVERED_DATE" DATE, 
	"ESTIMATED_TIME_DELIVERY" DATE
   );


CREATE TABLE "STG"."STG_ORDER_ITEMS" 
   (	"ORDER_ID" VARCHAR2(50), 
	"ORDER_ITEM_ID" NUMBER(10,0), 
	"PRODUCT_ID" VARCHAR2(50), 
	"SELLER_ID" VARCHAR2(50), 
	"PICKUP_LIMIT_DATE" DATE, 
	"PRICE" NUMBER(15,4), 
	"SHIPPING_COST" NUMBER(15,4)
   );


CREATE TABLE "STG"."STG_PAYMENTS" 
   (	"ORDER_ID" VARCHAR2(50), 
	"PAYMENT_SEQUENTIAL" NUMBER(10,0), 
	"PAYMENT_TYPE" VARCHAR2(50), 
	"PAYMENT_INSTALLMENTS" NUMBER(10,0), 
	"PAYMENT_VALUE" NUMBER(15,4)
   );


CREATE TABLE "STG"."STG_PRODUCTS" 
   (	"PRODUCT_ID" VARCHAR2(50), 
	"PRODUCT_CATEGORY" VARCHAR2(100), 
	"PRODUCT_NAME_LENGTH" NUMBER(10,0), 
	"PRODUCT_DESCRIPTION_LENGTH" NUMBER(10,0), 
	"PRODUCT_PHOTOS_QTY" NUMBER(10,0), 
	"PRODUCT_WEIGHT_G" NUMBER(15,0), 
	"PRODUCT_LENGTH_CM" NUMBER(10,0), 
	"PRODUCT_HEIGHT_CM" NUMBER(10,0), 
	"PRODUCT_WIDTH_CM" NUMBER(10,0)
   );


CREATE TABLE "STG"."STG_SELLERS" 
   (	"SELLER_ID" VARCHAR2(50), 
	"SELLER_ZIP_CODE" VARCHAR2(15), 
	"SELLER_CITY" VARCHAR2(100), 
	"SELLER_STATE" VARCHAR2(100)
   );


CREATE TABLE "STG"."STG_USERS" 
   (	"USER_NAME" VARCHAR2(50), 
	"CUSTOMER_ZIP_CODE" VARCHAR2(15), 
	"CUSTOMER_CITY" VARCHAR2(100), 
	"CUSTOMER_STATE" VARCHAR2(100)
   );